services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: roamandframe
      POSTGRES_USER: roamandframe
      POSTGRES_PASSWORD: roamandframe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
