dependencies {
	implementation project(':applications:ai-assistant:shared')
	implementation project(':applications:ai-assistant:modules:model-routing')
	implementation project(':applications:ai-assistant:modules:mcp-client')

	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}
